# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

h_GK_1D_exact <- function(xi, nh_max = 40L, tol = 0.000001) {
    .Call('_PCObw_h_GK_1D_exact', PACKAGE = 'PCObw', xi, nh_max, tol)
}

h_EK_1D_exact <- function(xi, nh_max = 40L, tol = 0.000001) {
    .Call('_PCObw_h_EK_1D_exact', PACKAGE = 'PCObw', xi, nh_max, tol)
}

h_BK_1D_exact <- function(xi, nh_max = 40L, tol = 0.000001) {
    .Call('_PCObw_h_BK_1D_exact', PACKAGE = 'PCObw', xi, nh_max, tol)
}

h_GK_1D_bin <- function(xi, nb_bin, nh_max = 40L, tol = 0.000001, adapt_nb_bin = FALSE) {
    .Call('_PCObw_h_GK_1D_bin', PACKAGE = 'PCObw', xi, nb_bin, nh_max, tol, adapt_nb_bin)
}

h_EK_1D_bin <- function(xi, nb_bin, nh_max = 40L, tol = 0.000001, adapt_nb_bin = FALSE) {
    .Call('_PCObw_h_EK_1D_bin', PACKAGE = 'PCObw', xi, nb_bin, nh_max, tol, adapt_nb_bin)
}

h_BK_1D_bin <- function(xi, nb_bin, nh_max = 40L, tol = 0.000001, adapt_nb_bin = FALSE) {
    .Call('_PCObw_h_BK_1D_bin', PACKAGE = 'PCObw', xi, nb_bin, nh_max, tol, adapt_nb_bin)
}

h_GK_mD_diag_exact <- function(x_i, nh_max, tol) {
    .Call('_PCObw_h_GK_mD_diag_exact', PACKAGE = 'PCObw', x_i, nh_max, tol)
}

h_GK_mD_full_exact <- function(x_i, S, nh_max, tol) {
    .Call('_PCObw_h_GK_mD_full_exact', PACKAGE = 'PCObw', x_i, S, nh_max, tol)
}

h_GK_binned_mD_diag <- function(x_i, nh_max, tol, nb_bin_per_axis = 32L, nb_bin_vect_ = NULL) {
    .Call('_PCObw_h_GK_binned_mD_diag', PACKAGE = 'PCObw', x_i, nh_max, tol, nb_bin_per_axis, nb_bin_vect_)
}

h_GK_binned_mD_full <- function(x_i, S, nh_max, tol, nb_bin_per_axis = 32L, nb_bin_vect_ = NULL) {
    .Call('_PCObw_h_GK_binned_mD_full', PACKAGE = 'PCObw', x_i, S, nh_max, tol, nb_bin_per_axis, nb_bin_vect_)
}

